name: flutter_moata
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8

  # flutter_naver_map 패키지를 pub.dev에서 버전 1.3.0으로 가져오기
  flutter_naver_map: ^1.3.0

  # geocoding 패키지 추가
  geocoding: ^2.1.1

  # http 패키지 추가 (최신 버전)
  http: ^1.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  change_app_package_name: ^1.4.0

flutter:
  uses-material-design: true
